# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VIPER-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIPER-Example
  pod 'Sourcery'

  target 'VIPER-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIPER-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
