# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVC-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVC-Example
  pod 'Sourcery'

  target 'MVC-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVC-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end